### ISSUE TITLE
Support for 3.5+?

### ISSUE THREAD

**Issue by shanegriffiths** [herrhelms/social-artboards-sketch#1]
Hello, does this plugin work in 3.5+?

**Comment by herrhelms** [comment]
Hey @shanegriffiths - it should work fine! I tried to test and install it via Sketch Toolbox and with manual download. Both versions worked fine on my computer (Sketch @ 3.5.2). It needs to run a little procedure once, to extend the existing artboard presets. Did you try that? Take a look at the `Plugin Menu -> Social Artboards -> Install Social Artboards`. Afterwards you should find "Social" presets whenever adding a new Artboard. If you discover any other problems, could you please reopen this issue and add some steps to reproduce? Thank's for getting in touch!
