### ISSUE TITLE
Don't work in version 3.6.1

### ISSUE THREAD

**Issue by marco-giacomuzzi** [herrhelms/social-artboards-sketch#2]
Ops!
Dont't works in Sketch version 3.6.1

Thanks!
![sketch](https://cloud.githubusercontent.com/assets/3425549/13496950/3d92772e-e153-11e5-9296-3980d3f965b2.png)

**Comment by herrhelms** [comment]
Hey @marco3w , sorry to hear you're having difficulties! Did you just download the plugin here from GitHub and then double clicked the .sketchPlugin file? That won't work. The plugin needs to reside in a subfolder within the Sketch Plugins Folder as mentioned in the README. 

If this is not helping you with your issue: Could you please reopen and provide more details for me how you installed the plugin?! And maybe add a screenshot of `~/Library/Application Support/com.bohemiancoding.sketch3` and `~/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3` - in any case please keep me posted.

**Comment by marco-giacomuzzi** [comment]
Hi @herrhelms, all done.
I have installed the plugin by Sketch Toolbox and not manually.
Thanks!!!

**Comment by herrhelms** [comment]
So, just to make sure: Did it work now? or "still not working" :)

**Comment by marco-giacomuzzi** [comment]
It work now ;)
