### ISSUE TITLE
Facebook cover size is no longer 851x315

### ISSUE THREAD

**Issue by NavitBar** [herrhelms/social-artboards-sketch#3]
Please update :)

> Displays at 828 pixels wide by 315 pixels tall on your Page on computers and 640 pixels wide by 360 pixels tall on smartphones

[Facebook help center](https://www.facebook.com/help/125379114252045)

**Comment by herrhelms** [comment]
took a while, but done! please read the "updates" section of the readme though. https://github.com/herrhelms/social-artboards-sketch#updates
